baseURL: /
languageCode: he-IL
title: 驻转 转拽
theme: PaperMod

defaultContentLanguage: he

enableRobotsTXT: true
outputs:
  home:
    - HTML
    - RSS
    - JSON

  pages:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: search
      name: 驻砖
      url: /search/

params:
  defaultTheme: dark
  disableThemeToggle: yes
  ShowBreadCrumbs: yes
  showtoc: yes
  ShowReadingTime: yes

  author:  拽专 住住拽
  DateFormat: "02.01.06"

  label:
    icon: /icon.svg

  homeInfoParams:
    title: 注转 拽  
    content: >
      住  转 住拽专驻 转转 驻砖转 驻转?
      转专  转爪 专, 转转, 驻 砖注专  驻  砖 砖,
      拽   -  注专转!

  socialIcons:
    - name: discord
      url: "https://discord.gg/kBK5J6Qmuc"
    - name: github
      url: "https://github.com/Advanced-Python"
    - name: rss
      url: "index.xml"
