baseURL: https://Advanced-Python.github.io/
languageCode: he-IL
title: 驻转 转拽
theme: PaperMod

defaultContentLanguage: he

enableRobotsTXT: true
outputs:
  home:
    - HTML
    - RSS
    - JSON

  pages:
    - HTML
    - RSS
    - JSON

params:
  defaultTheme: dark
  DateFormat: "2.1.06"
  ShowShareButtons: yes
  ShowReadingTime: yes

  homeInfoParams:
    title: 注转 拽  
    content: |
      住  转 住拽专驻 转转 驻砖转 驻转?
      - 转专  转爪 专, 转转, 驻 砖注专  驻  砖 砖
      - 拽   -  注专转!
